#!/bin/bash

# Simple dialog to show user the current status of pepper flash plugin

# Functions

function update(){
update-pepperflashplugin-nonfree --install --verbose |& yad --text-info --title="Adobe Flash Player" --window-icon=pepperflashplayer --image=pepperflashplayer --text="Forcing Pepper Flash update..."  --width 400 --height 300 --center --button=Finish:0 --class=pepper-flash-status --name=class=pepper-flash-status
}

function uninstall(){
update-pepperflashplugin-nonfree --uninstall --verbose |& yad --text-info --title="Adobe Flash Player" --window-icon=pepperflashplayer --image=pepperflashplayer --text="Uninstalling pepper flash plugin. Please wait..."  --width 400 --height 300 --center --button=Finish:0 --class=pepper-flash-status --name=class=pepper-flash-status
}

function license(){
cat /usr/local/lib/pepperflash-plugin-updater/google_eula.txt | yad --text-info --title="Google Terms of Service" --window-icon=pepperflashplayer --image=pepperflashplayer --text='<a href="http://www.google.com/intl/en/chrome/browser/privacy/eula_text.html">http://www.google.com/intl/en/chrome/browser/privacy/eula_text.html</a>' --width 600 --height 480 --center --button=Finish:0 --class=pepper-flash-status --name=class=pepper-flash-status
}

# Get current status:

current=$(update-pepperflashplugin-nonfree --status | grep "this system" | awk '{print $9}')
upstream=$(update-pepperflashplugin-nonfree --status | grep "upstream" | awk '{print $8}')

# Create dialog

yad --always-print-result --title="Adobe Flash Player" --center --window-icon=pepperflashplayer --button="Force Update":2 --button=Uninstall:3 --button=License:4 --button=Done:0 --image=pepperflashplayer --text="Cub Linux uses the Pepper Flash Player. To do this Google Chrome is downloaded, the Flash plugin is stripped out and placed where Chromium can find it. Chrome is not otherwise used. It is set to automatically update so you shouldn't need to force a manual update unless something has gone wrong.\n\nCurrent version: $current\nUpstream version: $upstream\n\n" --class=pepper-flash-status --name=class=pepper-flash-status

action=$?

# Do commands

case $action in
	0 ) exit 0 ;;
	1 ) exit 1 ;;
	2 ) update ;;
	3 ) uninstall ;;
	4 ) license ;;
	*) exit 1 ;;
esac
