#!/bin/bash
#
# this code will determine exactly the path and the type of object,
# then it will decide use l3afpad or nautilus to open it by ROOT permission
# http://ubuntuhandbook.org/index.php/2014/04/ubuntu-14-04-add-open-as-rootadministrator-to-context-menu/
#
# Determine the path
if [ -e -n $1 ]; then
obj="$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"
else
base="`echo $NAUTILUS_SCRIPT_CURRENT_URI | cut -d'/' -f3- | sed 's/%20/ /g'`"
obj="$base/${1##*/}"
fi
# Determine the type and run as ROOT
if [ -f "$obj" ]; then
gksu l3afpad "$obj"
elif [ -d "$obj" ]; then
gksu nautilus "$obj"
fi

exit 0